name: bbp_flutter
description: Best Bike Paths - Flutter demo
publish_to: "none"

version: 0.1.0+1

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    sensors_plus: ^6.0.0
    cupertino_icons: ^1.0.6
    flutter_riverpod: ^2.5.1
    geolocator: ^9.0.2
    dio: ^5.4.0
    uuid: ^4.5.2
    firebase_core: ^3.9.0
    firebase_auth: ^5.4.0
    google_sign_in: ^6.2.2

    google_maps_flutter: ^2.14.0
    flutter_polyline_points: ^3.1.0
    cloud_firestore: ^5.6.12
    geocoding: ^4.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true
